name: Code Quality

on:
  pull_request:
    branches: [development, staging, main]
  push:
    branches: [development]
    paths:
      - '**/*.cs'
      - '**/*.cshtml'
      - '**/*.csproj'

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format
      
      - name: Format code
        run: dotnet format
      
      - name: Commit formatting changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/development'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply automatic code formatting"
          file_pattern: "**/*.cs"
