name: Code Quality

on:
  pull_request:
    branches: [development, staging, main]
  push:
    branches: [development]
    paths:
      - '**/*.cs'
      - '**/*.cshtml'
      - '**/*.csproj'

jobs:
  analyze:
    name: Analyze Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
      
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      
      - name: Check code formatting
        run: |
          dotnet tool install --global dotnet-format
          dotnet format --verify-no-changes --verbosity diagnostic
      
      - name: Begin SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Generated from SonarCloud account
        run: |
          dotnet sonarscanner begin /k:"your-project-key" \
            /o:"your-organization" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.dotcover.reportsPaths=coverage.xml \
            /d:sonar.cpd.cs.minimumLines=6 \
            /d:sonar.cpd.cs.minimumTokens=50 \
            /d:sonar.qualitygate.wait=true
      
      - name: Build project
        run: dotnet build --no-incremental
      
      - name: Run tests (excluding BDD tests)
        run: |
          dotnet-coverage collect 'dotnet test --filter "FullyQualifiedName!~DataPrivacyAuditTool.Tests.BDD"' -f xml -o 'coverage.xml'
      
      - name: End SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      
      - name: Setup Node.js for code duplication analysis
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Run Code Duplication Check
        run: jscpd --min-lines 6 --min-tokens 50 --threshold 1 --reporters "html,console" --output ./jscpd-report .
        
      - name: Upload duplication report
        uses: actions/upload-artifact@v4
        with:
          name: duplication-report
          path: ./jscpd-report
