version: 2
updates:
  # Enable version updates for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    # Open PRs against development branch
    target-branch: "development"
    reviewers:
      - "Arno-ATU"
    # Group updates by type
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Arno-ATU"
