name: Deploy

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches: [development, staging, main]

jobs:
  deploy:
    # Only run if tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      # Deployment based on branch
      - name: Deploy to Development
        if: github.event.workflow_run.head_branch == 'development'
        run: |
          echo "Deploying to Development environment"
          dotnet publish -c Release -o ./publish
          
      
      - name: Deploy to Staging
        if: github.event.workflow_run.head_branch == 'staging'
        run: |
          echo "Deploying to Staging environment"
          dotnet publish -c Release -o ./publish
          
      
      - name: Deploy to Production
        if: github.event.workflow_run.head_branch == 'main'
        run: |
          echo "Deploying to Production environment"
          dotnet publish -c Release -o ./publish
          
      
      - name: Deployment Report
        run: |
          echo "Deployment completed successfully"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Environment: $(if [[ '${{ github.event.workflow_run.head_branch }}' == 'main' ]]; then echo 'Production'; elif [[ '${{ github.event.workflow_run.head_branch }}' == 'staging' ]]; then echo 'Staging'; else echo 'Development'; fi)"

      # Simple Deployment Report
      - name: Generate Deployment Report
        id: deployment-report
        run: |
          # Create reports directory
          mkdir -p reports
          
          # Determine environment name
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            ENVIRONMENT="Production"
          elif [[ "${{ github.event.workflow_run.head_branch }}" == "staging" ]]; then
            ENVIRONMENT="Staging"
          else
            ENVIRONMENT="Development"
          fi
          
          # Generate a simple report
          cat > "reports/deployment-${{ github.run_id }}.md" << EOF
          # Deployment Report
          
          **Environment:** ${ENVIRONMENT}
          **Date:** $(date -u "+%Y-%m-%d %H:%M:%S UTC")
          **Branch:** ${{ github.event.workflow_run.head_branch }}
          **Run ID:** ${{ github.run_id }}
          
          ## Recent Changes
          $(git log -5 --pretty=format:"* %h %s (%an)" --date=short)
          
          ## Notes
          $(if [[ "${ENVIRONMENT}" == "Production" ]]; then 
              echo "⚠️ Production deployment - please verify critical functionality"; 
            else 
              echo "Standard ${ENVIRONMENT} deployment"; 
            fi)
          EOF
          
          echo "report_path=reports/deployment-${{ github.run_id }}.md" >> $GITHUB_OUTPUT
          echo "environment=${ENVIRONMENT}" >> $GITHUB_OUTPUT

      # Upload the report as an artifact
      - name: Upload Deployment Report
        uses: actions/upload-artifact@v4
        with:
          name: deployment-report-${{ github.run_id }}
          path: ${{ steps.deployment-report.outputs.report_path }}
          retention-days: 30
