name: Run Tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ development, staging, main ]

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: build-artifacts
          path: .
      
      - name: List downloaded artifacts (debug)
        run: find . -type f -path "*/bin/Release/*" | head -n 10
      
      - name: Run unit tests with artifacts
        run: dotnet test ./src/DataPrivacyAuditTool.Tests.Unit/DataPrivacyAuditTool.Tests.Unit.csproj --no-build
        
      - name: Mark workflow as successful
        if: success()
        run: echo "Tests completed successfully"
