name: Run Tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: [ development, staging, main ]

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: build-artifacts
          path: .
      
      - name: List downloaded artifacts (debug)
        run: find . -type f -path "*/bin/Release/*" | head -n 10
      
      - name: Run unit tests with artifacts
        run: dotnet test ./src/DataPrivacyAuditTool.Tests.Unit/DataPrivacyAuditTool.Tests.Unit.csproj --no-build --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
      
      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Test Results
          path: "**/TestResults/test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true
      
      - name: Generate code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
        if: success() || failure()
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlInline;Cobertura"
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: coverage-report
          path: coveragereport
          retention-days: 5
